[datapath]
data_path = dataset
db_vector_path=database/chromadb

[model_type]
openai = False
huggingface = False
gemini = True
ollama= True

[stages_flags]
data_ingestion = True
chroma_vectorstore = True
modelling = True
model_evaluation = False

