[data_params]
recursive_split = True
character_split = False
chunk_size = 1000
chunk_overlap = 100
collection_name=rag_documents

[embedding]
gemini_embedding_model= models/text-embedding-004
ollama_embedding_model=nomic-embed-text:latest 
db_type = chroma


[model_params]
gemini_model = gemini-1.5-flash
ollama_model=qwen3:8b
openai_model_name = None
huggingface_model_name =TinyLlama/TinyLlama-1.1B-Chat-v1.0
temprature = 0.6
security_model =phi:2.7b

